server:
  port: 13700

spring:
  application:
    name: mcp-server
  profiles:
    active: dev
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        type: async

logging:
  level:
    root: info
