server:
  port: 13600

spring:
  application:
    name: mcp-client
  profiles:
    active: dev

langchain4j:
  open-ai:
    streaming-chat-model:
      model-name: ${DOUBAO_MODEL_NAME}
      api-key: ${DOUBAO_API_KEY}
      base-url: https://ark.cn-beijing.volces.com/api/v3/
      log-requests: true
      log-responses: true


logging:
  level:
    root: info
