server:
  port: 15977

spring:
  application:
    name: mcp-agent
  profiles:
    active: dev
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com

logging:
  level:
    root: info
