server:
  port: 15977

spring:
  application:
    name: mcp-agent
  profiles:
    active: dev
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 1.1
    chat:
      observations:
        log-completion: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

volc:
  tts:
    app-id: ${VOLC_TTS_APP_ID}
    access-token: ${VOLC_TTS_ACCESS_TOKEN}
    endpoint: wss://openspeech.bytedance.com/api/v3/tts/bidirection
    encoding: mp3
    voice: zh_female_tianxinxiaomei_emo_v2_mars_bigtts

logging:
  level:
    root: info
