server:
  port: 15977

spring:
  application:
    name: mcp-agent
  profiles:
    active: dev
  ai:
    deepseek:
      api-key: ${DOUBAO_API_KEY}
      chat:
        base-url:  https://ark.cn-beijing.volces.com
        completions-path: /api/v3/chat/completions
        options:
          model: ${DOUBAO_MODEL_NAME}

logging:
  level:
    root: info
